# Generated by Django 4.2.4 on 2023-09-28 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comments_remove_post_tags_delete_tag_comments_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='text',
            field=models.TextField(default='default'),
        ),
    ]
